name = "ogmash-v2"
account_id = "a6533d1b483e8ab51c031e0c7c27ba9a"
workers_dev = true

main = "_worker.js"

compatibility_date = "2023-12-01"

[[r2_buckets]]
binding = "ogmash_BUCKET"
bucket_name = "ogmash"

