import Image from "next/image";
import localFont from "next/font/local";
import siteConfig from "../styles/site-config.json";
import { useState, useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export default function Home() {
  const [isMobile, setIsMobile] = useState(true);

  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 768);
    };
    
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  return (
    <div 
      className={`${geistSans.variable} min-h-screen flex flex-col items-center`}
      style={{ backgroundColor: siteConfig.colors.background.main }}
    >
      {/* Header Banner Section */}
      <div 
        className="w-full overflow-hidden relative"
        style={{ 
          height: isMobile ? siteConfig.headerBanner.mobile.height : siteConfig.headerBanner.desktop.height
        }}
      >
        <Image 
          src="/assets/header-banner.jpg" 
          alt="Header Banner" 
          className="object-cover"
          fill
          priority
          sizes="100vw"
          style={{ 
            transform: isMobile ? siteConfig.headerBanner.mobile.transform : siteConfig.headerBanner.desktop.transform
          }}
        />
      </div>

      {/* Mission Statement Section */}
      <div className="w-11/12 md:w-4/5 mx-auto text-left py-4 md:py-8">
        <p style={{ 
          color: siteConfig.colors.text.primary,
          fontSize: isMobile ? siteConfig.typography.fontSize.lg : siteConfig.typography.fontSize["2xl"]
        }}>
          OGMASH is an American &quot;YURU-CHARA&quot; musical act that consists of a solo drummer that plays to and DJs songs written by the performer. All songs performed are original copy written works of musical art. The lyrical content tends to be that of inner self reflection, but sometimes the songs are just for fun. Some are serious subjects and some are not.<br/><br/> 
          OG is the performer in Digital form. He only exists in a digital video jukebox.<br/><br/>
          He is the last of his model and soon to be replaced by upgraded models. OG is first of a long line of American &quot;YURU CHARA&quot; who&apos;s sole purpose is raise funds and awareness for a Rottweiler Canine Rescue called &quot;ChascaPark&quot; TM. ChascaPark&apos;s goal is to be a national foundation dedicated to the health and betterment of the Rottweiler breed while offering dedicated canine assistance to American Military Veterans.<br/><br/>
          All funds generated by OG and OGMASH go to the ChascaPark Rottweiler Rescue.
        </p>
      </div>

      {/* Showtimes Section */}
      <div className="w-11/12 md:w-4/5 mx-auto relative py-4 md:py-8">
        <Image 
          src="/assets/SHOWTIMES.png" 
          alt="Showtimes" 
          className="w-full"
          width={700}
          height={475}
          style={{ height: 'auto' }}
        />
      </div>
    </div>
  );
}
